// <auto-generated />
using JF.AgenticEnterprise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JF.AgenticEnterprise.Infrastructure.Migrations
{
    [DbContext(typeof(InboxDbContext))]
    [Migration("20260615065832_Sprint3_AgentConflicts_WorkflowKnowledge")]
    partial class Sprint3_AgentConflicts_WorkflowKnowledge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AgentConflict", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SourceConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TargetConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowId", "ConflictType");

                    b.ToTable("AgentConflicts");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AgentExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("EmailId", "AgentType");

                    b.HasIndex("WorkflowId", "StartedAt");

                    b.ToTable("AgentExecutions");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentType")
                        .HasColumnType("TEXT");

                    b.Property<float>("DocumentTypeConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EmailId", "OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Classification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OverriddenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverriddenBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalsDetectedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("CategoryType", "CreatedAt");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.ContractAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ContractType")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyObligationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalClause")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("ContractAnalyses");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.ContractExtraction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreementType")
                        .HasColumnType("TEXT");

                    b.Property<float>("AgreementTypeConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AutoRenewal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutoRenewalNoticeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculatedAlertDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("EffectiveDateConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("ExpiryDateConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("GoverningLaw")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LiabilityCapAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiabilityCapCurrency")
                        .HasColumnType("TEXT");

                    b.Property<float>("OverallConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("PartyA")
                        .HasColumnType("TEXT");

                    b.Property<float>("PartyAConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("PartyB")
                        .HasColumnType("TEXT");

                    b.Property<float>("PartyBConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("TerminationForConvenience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.ToTable("ContractExtractions");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Email", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPlainText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HumanReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IngestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessingDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawStoragePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SenderEmail");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.HumanReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<float>("AgentConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverrideCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConflictId");

                    b.HasIndex("EmailId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("Status", "Priority", "QueuedAt");

                    b.ToTable("HumanReviews");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.InvoiceAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("InvoiceAnalyses");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.InvoiceExtraction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("DueDateConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("InvoiceDateConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<float>("InvoiceNumberConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("LineItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("OverallConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoReference")
                        .HasColumnType("TEXT");

                    b.Property<float>("PoReferenceConfidence")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalAmountConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ValidationChecksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .HasColumnType("TEXT");

                    b.Property<float>("VendorNameConfidence")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.ToTable("InvoiceExtractions");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.OrchestrationDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("OrchestrationDecisions");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.RiskFlag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ContractExtractionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageReference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractExtractionId");

                    b.HasIndex("Severity");

                    b.ToTable("RiskFlags");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedSignalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MatchConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ProposalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmailId");

                    b.HasIndex("ProposalId");

                    b.ToTable("TaxonomyCandidates");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Routing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedExtractionFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalClassifiedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("TaxonomyCategories");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyProposal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultingCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SampleEmailIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedExtractionFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedRouting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultingCategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId");

                    b.ToTable("TaxonomyProposals");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Workflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictReportJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeType")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowKnowledge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApprovedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedCategory")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("CurrentConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentReasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("InitialConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("RefinedCategory")
                        .HasColumnType("TEXT");

                    b.Property<float?>("RefinedConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("RefinedReasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedCategory")
                        .HasColumnType("TEXT");

                    b.Property<float?>("SuggestionConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("SuggestionReasoning")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowKnowledge");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ClassificationConfidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutedToAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractAnalysisId");

                    b.HasIndex("InvoiceAnalysisId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowResults");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSummary")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "StepOrder");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AgentConflict", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithMany("AgentConflicts")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AgentExecution", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany("AuditEntries")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Classification", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("Classification")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.Classification", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.ContractAnalysis", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("ContractAnalysis")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.ContractAnalysis", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithOne("ContractAnalysis")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.ContractAnalysis", "WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.ContractExtraction", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("ContractExtraction")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.ContractExtraction", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Attachment");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.HumanReview", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentConflict", "Conflict")
                        .WithMany("HumanReviews")
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany("HumanReviews")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithMany("HumanReviews")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conflict");

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.InvoiceAnalysis", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("InvoiceAnalysis")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.InvoiceAnalysis", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithOne("InvoiceAnalysis")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.InvoiceAnalysis", "WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.InvoiceExtraction", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("InvoiceExtraction")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.InvoiceExtraction", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Attachment");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.OrchestrationDecision", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithOne("OrchestrationDecision")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.OrchestrationDecision", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.RiskFlag", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.ContractExtraction", "ContractExtraction")
                        .WithMany("RiskFlags")
                        .HasForeignKey("ContractExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractExtraction");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyCandidate", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany("TaxonomyCandidates")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.TaxonomyProposal", "Proposal")
                        .WithMany("Candidates")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Email");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyProposal", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.TaxonomyCategory", "ResultingCategory")
                        .WithMany()
                        .HasForeignKey("ResultingCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResultingCategory");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithOne("Workflow")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.Workflow", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowKnowledge", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithOne("WorkflowKnowledge")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.WorkflowKnowledge", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowResult", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.ContractAnalysis", "ContractAnalysis")
                        .WithMany()
                        .HasForeignKey("ContractAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.InvoiceAnalysis", "InvoiceAnalysis")
                        .WithMany()
                        .HasForeignKey("InvoiceAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithOne("WorkflowResult")
                        .HasForeignKey("JF.AgenticEnterprise.Domain.Entities.WorkflowResult", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractAnalysis");

                    b.Navigation("InvoiceAnalysis");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("JF.AgenticEnterprise.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.AgentConflict", b =>
                {
                    b.Navigation("HumanReviews");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.ContractExtraction", b =>
                {
                    b.Navigation("RiskFlags");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Email", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("Attachments");

                    b.Navigation("AuditEntries");

                    b.Navigation("Classification");

                    b.Navigation("ContractAnalysis");

                    b.Navigation("ContractExtraction");

                    b.Navigation("HumanReviews");

                    b.Navigation("InvoiceAnalysis");

                    b.Navigation("InvoiceExtraction");

                    b.Navigation("TaxonomyCandidates");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.TaxonomyProposal", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("JF.AgenticEnterprise.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("AgentConflicts");

                    b.Navigation("AgentExecutions");

                    b.Navigation("ContractAnalysis");

                    b.Navigation("HumanReviews");

                    b.Navigation("InvoiceAnalysis");

                    b.Navigation("OrchestrationDecision");

                    b.Navigation("Steps");

                    b.Navigation("WorkflowKnowledge");

                    b.Navigation("WorkflowResult");
                });
#pragma warning restore 612, 618
        }
    }
}
